# Deployment do mongodb
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.6
        ports:
        - containerPort: 27027
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongouser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongopwd
---
# Service MongoDB
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27027
  type: ClusterIP
---
# Deployment do python
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rotten-potatoes
spec:
  selector:
    matchLabels:
      app: rotten-potatoes
  template:
    metadata:
      labels:
        app: rotten-potatoes
    spec:
      containers:
      - name: rotten-potatoes
        image: lelebs/rotten-potatoes:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        env:
          - name: MONGODB_DB
            value: "admin"
          - name: MONGODB_HOST
            value: "mongodb"
          - name: MONGODB_PORT
            value: "27027"
          - name: MONGODB_USERNAME
            value: "mongouser"
          - name: MONGODB_PASSWORD
            value: "mongopwd"
---
# Service python
apiVersion: v1
kind: Service
metadata:
  name: rotten-potatoes
spec:
  selector:
    app: rotten-potatoes
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  type: NodePort
